# Check for mandatory parameters

- fail: msg="es_instance_name must be specified"
  when: es_instance_name is not defined

- fail: msg="Parameter 'http.port' must be defined when multicast is disabled"
  when: es_config['discovery.zen.ping.multicast.enabled'] == false or (es_version | version_compare('2.0', '>=') and es_config['discovery.zen.ping.multicast.enabled'] is not defined) and es_config['http.port'] is not defined

- fail: msg="Parameter 'transport.tcp.port' must be defined when multicast is disabled"
  when: es_config['discovery.zen.ping.multicast.enabled'] == false or (es_version | version_compare('2.0', '>=') and es_config['discovery.zen.ping.multicast.enabled'] is not defined) and es_config['transport.tcp.port'] is not defined

- fail: msg="Parameter 'discovery.zen.ping.unicast.hosts' must be defined when multicast is disabled"
  when: es_config['discovery.zen.ping.multicast.enabled'] == false or (es_version | version_compare('2.0', '>=') and es_config['discovery.zen.ping.multicast.enabled'] is not defined) and es_config['discovery.zen.ping.unicast.hosts'] is not defined

# If multicast is false OR if > 2.0 AND not defined as true (or explicitly false)