---
# Trigger Debian section
- name: Include Debian specific Elasticsearch
  include: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'

# Trigger Redhat section
- name: Include RedHat specific Elasticsearch
  include: elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Make sure the service is started, and restart if necessary
- name: Start elasticsearch service
  service: name=elasticsearch state=started
  when: es_start_service
  register: elasticsearch_started
- name: Restart elasticsearch service if new version installed
  service: name=elasticsearch state=restarted
  when: es_start_service and 
    ( elasticsearch_install.changed or elasticsearch_configure.changed )
    and not elasticsearch_started.changed
