---
- name: Copy templates to elasticsearch
  copy: src=templates dest=/etc/elasticsearch/

- name: Wait for elasticsearch to startup
  wait_for: port=9200 delay=10

- name: Get template files 
  shell: find . -maxdepth 1 -type f | sed "s#\./##" | sed "s/.json//" chdir=/etc/elasticsearch/templates
  register: resultstemplate

- name: Install template(s)
  command: 'curl -sL -XPUT http://localhost:9200/_template/{{item}} -d @/etc/elasticsearch/templates/{{item}}.json'
  with_items: resultstemplate.stdout_lines
