---

- set_fact: es_binary_prefix=""

- set_fact: es_binary_prefix="elasticsearch-"
  when: es_version | version_compare('5.0', '>=')

- name: Include optional user and group creation.
  when: (es_user_id is defined) and (es_group_id is defined)
  include: elasticsearch-optional-user.yml

- name: Include specific Elasticsearch
  include: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Elasticsearch
  include: elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'
