---
- name: RedHat - Ensure Java is installed
  yum: name={{ java_rhel }} state=latest
  when: ansible_os_family == 'RedHat'
  
- name: Debian - Ensure Java is installed
  apt: name={{ java_debian }} state=present update_cache=yes
  when: ansible_os_family == 'Debian'