---
- name: Java - Define java_packages.
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined  

- name: Include Debian specific Java stuff
  include: java-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include RedHat specific Java stuff
  include: java-RedHat.yml
  when: ansible_os_family == 'RedHat'


