---
#Check if license is installed
- name: Check License is installed
  shell: >
    {{es_home}}/bin/plugin list | tail -n +2 | grep license
  register: license_installed
  ignore_errors: yes
  changed_when: False
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"

#Remove license if installed and xpack not enabled
- name: Remove license plugin
  command: >
    {{es_home}}/bin/plugin remove license
  register: license_change
  failed_when: "'ERROR' in license.stdout"
  changed_when: license_change.rc == 1
  when: license_installed.rc == 0 and not es_enable_xpack
  notify: restart elasticsearch
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"


#Install License if not installed
- name: Install license plugin
  command: >
    {{es_home}}/bin/plugin install license
  register: license_change
  failed_when: "'ERROR' in license_change.stdout"
  changed_when: license_change.rc == 0
  when: license_installed.rc == 1 and es_enable_xpack
  notify: restart elasticsearch
  environment:
    CONF_DIR: "{{ conf_dir }}"
    ES_INCLUDE: "{{ instance_default_file }}"

#Include shield as we may need to remove it
- include: shield/elasticsearch-shield.yml
#  when: '"shield" in es_xpack_features'

#Any other xpacks plugins requiring configuration to be entered here

- name: Set Plugin Directory Permissions
  file: state=directory path={{ es_home }}/plugins owner={{ es_user }} group={{ es_group }} recurse=yes